In [6]:
N, H, W, C = 2, 5, 7, 3
x = tf.reshape(tf.range(N * H * W * C, dtype=tf.float32), [N, H, W, C])

### Batch Normalization 1

Results from `batch_normalization`, same behaviour as `torch.nn.BatchNorm2d(C)`

In [23]:
print(batch_normalization(x))

tf.Tensor(
[[[[-1.7074814  -1.7074814  -1.7074814 ]
   [-1.6579893  -1.6579893  -1.6579893 ]
   [-1.608497   -1.608497   -1.608497  ]
   [-1.5590048  -1.5590048  -1.5590048 ]
   [-1.5095125  -1.5095125  -1.5095125 ]
   [-1.4600203  -1.4600203  -1.4600203 ]
   [-1.4105282  -1.4105282  -1.4105282 ]]

  [[-1.361036   -1.361036   -1.361036  ]
   [-1.3115437  -1.3115437  -1.3115437 ]
   [-1.2620515  -1.2620515  -1.2620515 ]
   [-1.2125593  -1.2125593  -1.2125593 ]
   [-1.1630671  -1.1630671  -1.1630671 ]
   [-1.1135749  -1.1135749  -1.1135749 ]
   [-1.0640826  -1.0640826  -1.0640826 ]]

  [[-1.0145904  -1.0145904  -1.0145904 ]
   [-0.9650982  -0.9650982  -0.9650982 ]
   [-0.91560596 -0.91560596 -0.91560596]
   [-0.8661138  -0.8661138  -0.8661138 ]
   [-0.81662154 -0.81662154 -0.81662154]
   [-0.76712936 -0.76712936 -0.76712936]
   [-0.7176371  -0.7176371  -0.7176371 ]]

  [[-0.66814494 -0.66814494 -0.66814494]
   [-0.6186527  -0.6186527  -0.6186527 ]
   [-0.56916046 -0.56916046 -0.56916046]

### Layer Normalization 1

Results from `layer_normalization`, same behaviour as `torch.nn.LayerNorm((C, H, W))`.

In [22]:
print(layer_normalization(x))

tf.Tensor(
[[[[-1.7156329e+00 -1.6826400e+00 -1.6496470e+00]
   [-1.6166540e+00 -1.5836611e+00 -1.5506682e+00]
   [-1.5176753e+00 -1.4846823e+00 -1.4516894e+00]
   [-1.4186964e+00 -1.3857036e+00 -1.3527106e+00]
   [-1.3197176e+00 -1.2867247e+00 -1.2537317e+00]
   [-1.2207388e+00 -1.1877459e+00 -1.1547530e+00]
   [-1.1217600e+00 -1.0887671e+00 -1.0557741e+00]]

  [[-1.0227811e+00 -9.8978823e-01 -9.5679533e-01]
   [-9.2380238e-01 -8.9080942e-01 -8.5781652e-01]
   [-8.2482356e-01 -7.9183060e-01 -7.5883770e-01]
   [-7.2584474e-01 -6.9285184e-01 -6.5985888e-01]
   [-6.2686592e-01 -5.9387302e-01 -5.6088006e-01]
   [-5.2788711e-01 -4.9489418e-01 -4.6190125e-01]
   [-4.2890832e-01 -3.9591539e-01 -3.6292243e-01]]

  [[-3.2992950e-01 -2.9693657e-01 -2.6394361e-01]
   [-2.3095068e-01 -1.9795775e-01 -1.6496481e-01]
   [-1.3197188e-01 -9.8978937e-02 -6.5986000e-02]
   [-3.2993063e-02 -1.2585807e-07  3.2992810e-02]
   [ 6.5985747e-02  9.8978683e-02  1.3197163e-01]
   [ 1.6496456e-01  1.9795750e-01  

### Layer Normalization 2

Results from `layer_normalization_tfsim`, same behaviour as `tf.keras.layers.LayerNormalization()`.

In [24]:
print(layer_normalization_tfsim(x))

tf.Tensor(
[[[[-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]]

  [[-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]]

  [[-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]]

  [[-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]
   [-1.224653  0.        1.224653]]

 

### Layer Normalization - Torch

Layer Normalization result of `tf.keras.layers.LayerNormalization()`

In [25]:
print(tf.keras.layers.LayerNormalization()(x))

tf.Tensor(
[[[[-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]]

  [[-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]]

  [[-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]]

  [[-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238274]
   [-1.2238274  0.         1.2238

### Batch Normalization - Keras

Suspicious Batch Normalization Result of `tf.keras.layers.BatchNormalization()`

In [26]:
print(tf.keras.layers.BatchNormalization()(x))

tf.Tensor(
[[[[  0.           0.99950033   1.9990007 ]
   [  2.998501     3.9980013    4.997502  ]
   [  5.997002     6.9965024    7.9960027 ]
   [  8.995503     9.995004    10.994504  ]
   [ 11.994004    12.993505    13.993005  ]
   [ 14.992505    15.992005    16.991507  ]
   [ 17.991007    18.990507    19.990007  ]]

  [[ 20.989508    21.989008    22.988508  ]
   [ 23.988008    24.987509    25.98701   ]
   [ 26.98651     27.98601     28.98551   ]
   [ 29.98501     30.98451     31.98401   ]
   [ 32.983513    33.983013    34.982513  ]
   [ 35.982014    36.981514    37.981014  ]
   [ 38.980515    39.980015    40.979515  ]]

  [[ 41.979015    42.978516    43.978016  ]
   [ 44.977516    45.977016    46.976517  ]
   [ 47.976017    48.975517    49.975018  ]
   [ 50.974518    51.97402     52.97352   ]
   [ 53.97302     54.97252     55.97202   ]
   [ 56.97152     57.97102     58.97052   ]
   [ 59.97002     60.96952     61.96902   ]]

  [[ 62.96852     63.96802     64.96752   ]
   [ 65.967026 